### ISSUE TITLE
📚 Documentation: Where do I get the Documentation

### ISSUE THREAD

**Issue by kezenwa** [utopia-php/framework#71]
### 💭 Description

Where do I get the 📚 Documentation ?

I'm trying out this frameWork but can't seem to find it's documentation and features of the frameWork. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Most of the docs are available either on the readme or the source code itself. Obviously this is not perfect, but we do plan to launch a doc site in the near future.

**Comment by stnguyen90** [comment]
@kezenwa, this [Getting Started Guide](https://github.com/utopia-php/framework/blob/master/docs/Getting-Starting-Guide.md) might be helpful.
